### VM variables
## Which image format to use
# qcow2
# vmdk
# raw
ImageFormat: vmdk

## New VM ID number
NewVmID: "240"

## New VM name
NewVmName: "MiB-Host"

## New account username
NewVmUsername: mib

## New account password must be the same as pve node sudo password
NewVmPassword: "{{ansible_become_pass}}"

## VM's IP address
NewVmIP: 10.0.1.240

### Inventory SSH Variables
# Pve node sudo password
ansible_become_pass: [key in pve node sudo password]
# SSH VM username
ansible_user: "{{NewVmUsername}}"
# SSH VM IP address
ansible_host: "{{NewVmIP}}"
# SSH jumphost option
ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q [Key in Jumphost IP] -p [Key in Jumphost Port Number]"'
