- name: copy web-backend service file into VM
  copy:
    src: "{{item}}"
    dest: /etc/systemd/system/
  with_items:
    - services/web-backend.service
    - services/web-frontend.service

- name: Enable and start up web-backend service
  systemd:
    name: "{{item}}" 
    state: started
    enabled: yes
  with_items:
    - web-backend.service
    - web-frontend.service
