- name: Create MiB VM using Cloud-Init Image Template
  hosts:
    pve_node
  become: yes
  roles:
    - role: create_vm
      tags: create_vm

- name: Setup MiB
  hosts:
    mib_host
  become: yes
  roles:
    - role: mib_setup
      tags: mib_setup
