- name: Configure VM's Useraccount using cloudinit (Username, Password & IP address)
  shell: "qm set {{item.0}} --ciuser {{NewVmUsername}} --cipassword {{NewVmPassword}} --ipconfig0 ip={{item.1}}/24,gw={{GwIP}} --net0 virtio,bridge=vmbr0{{VlanTag}}"
  loop: "{{ NewVmID|zip(NewVmIP,PveNode)|list }} "
  when: ansible_hostname == item.2

- name: copy ssh key of ansible host machine to target machine
  copy:
    src: sshpubkeys
    dest: /sshkey
  loop: "{{PveNode}}"
  when: ansible_hostname == item

- name: Configure VM's Useraccount using cloudinit (SSH)
  shell: "qm set {{item.0}} --sshkey /sshkey"
  loop: "{{ NewVmID|zip(PveNode)|list }}"
  when: ansible_hostname == item.1

- name: Configure VM's Useraccount using cloudinit (DNS)
  shell: "qm set {{item.0}} --nameserver '{{DNSIP}}' --searchdomain '{{DNSdomain}}'"
  loop: "{{ NewVmID|zip(PveNode)|list }}"
  when: ansible_hostname == item.1
