- name: Create a vm for MiB setup
  block:
  - name: Spin off new vm
    import_tasks: spinoff_vm.yaml

  - name: Create useraccount using cloudinit feature
    import_tasks: create_useraccount.yaml

  - name: Start up vm
    import_tasks: start_vm.yaml

  delegate_to: "{{PveNode}}"
