OUTDATED_MESSAGE_THRESHOLD_SECONDS = 120  # reduce this number in production environment
OUTDATED_IKB = 'Session expire. Please try again'
LOGGER_NAME = 'IssLoggerName'
TICKET_MAX_LENGTH = 500
PHOTO_MAX_SIZE = 2 * 1024 * 1024
PLACE_HOLDER_CHAT_ID = 0
LISTING_MAX_LENGTH = 4080
OVERVIEW_MAX_DAYS = 8
USER_REJECT_REGISTRATION = 'Reject'
ERROR_CDOE_OK = 0
CONFIRMATION_YES = 'YES'
CONFIRMATION_NO = 'NO'
BOOKING_APPROVE = 'Approve'
BOOKING_REJECT = 'Reject'
LAYOUT_CONFIRMATION_PER_ROW = 2
LAYOUT_BOOKING_APPROVAL_PER_ROW = 2
LAYOUT_DURATION_PER_ROW = 3
LAYOUT_ROOM_PER_ROW = 1
LAYOUT_TIMING_PER_ROW = 4
LAYOUT_BLOCKBOOK_DURATION_PER_ROW = 4
LAYOUT_ROOM_CATEGORY_PER_ROW = 3
LAYOUT_LOCATION_CATEGORY_PER_ROW = 2
LAYOUT_BLOCKBOOK_USAGE_PER_ROW = 1
LAYOUT_BOOKING_LIST_PER_ROW = 1
LAYOUT_LIST_RANGE_PER_ROW = 2
ROOM_CATEGORIES = [{"1-4": 4}, {"5-8": 8}, {"9-18": 18}]
LOCATION_CATEGORIES = [{"O2 Level 6": "O2_L6"}, {"O1 Level 4": "O1_L4"}, {"O1 Level 5": "O1_L5"}, {"O1 Level 6": "O1_L6"}]
LOCK_TIMINGS = ['0900', '1000', '1100', '1200', '1300', '1400', '1500', '1600', '1700', '1800']
BLOCKBOOK_DAYS = [2, 3, 4, 5]
BLOCKBOOK_USAGE = ['Design Review', 'Training', 'Others']
LIST_RANGE = [{"Within 30 days": '30'}, {"All": 'All'}]
CALENDAR_SELF_GEN = 0
CALENDAR_REQ_NORMAL = 1
CALENDAR_REQ_BLOCK = 2
CALENDAR_MAX_FUTURE_DAYS = 180
TEST_ERROR_CODE_NOK = 99
TEST_STRING_ANYTHING = 'ANYTHING'
TEST_STRING_CALLBACK = 'CALLBACK^STRING'
TEST_PHONE = '6596271787'
TEST_PHONE_ADMIN = '6594559122'
TEST_NAME = 'superhero'
TEST_NAME_ADMIN_1 = 'magneto'
TEST_NAME_ADMIN_2 = 'captain'
TEST_ADMIN_ID_1 = 889933
TEST_ADMIN_ID_2 = 889944
TEST_ADMIN_EMPLOYEE_ID_1 = 111
TEST_ADMIN_EMPLOYEE_ID_2 = 222
TEST_ADMIN_CHAT_ID_1 = 101433995  # JC
TEST_ADMIN_CHAT_ID_2 = 69973472  # DL
TEST_USER_ID = 223344
TEST_USER_EMPLOYEE_ID = 444
TEST_CHAT_ID = 556677
TEST_DUMB_ID = 667788
TEST_DUMB_EMPLOYEE_ID = 333
TEST_DUMB_CHAT_ID = 778899
TEST_DUMB_NAME = 'dumbo'
TEST_DUMB_PHONE = '995'
TEST_ROOM_CAPACITY = 9
TEST_DURATION = 3
TEST_USAGE = 'Meeting'
TEST_ROOM_NAME = 'Ruby'
TEST_BOOK_ID = 888
TEST_SELECTED_START_DATE = '250319'
TEST_SELECTED_END_DATE = '210125'
TEST_SELECTED_START_TIME = '0900'
TEST_SELECTED_END_TIME = '1700'
TEST_HTML_FILELOCATION = 'overview.html'
BOT_STATE_KEY_CALLBACK_STRING = 'keyCallbackStr'
BOT_STATE_KEY_FREE_TEXT = 'keyFreeText'
BOT_STATE_KEY_FREE_TEXT_DEFAULT = 'NA'
BOT_STATE_KEY_SUBMISSION_DESCRIPTION = 'keyTicketDescription'
BOT_STATE_KEY_SUBMISSION_EMAIL = 'keyTicketEmail'
CALLBACK_NO_ACTION = 'NIL'
CALLBACK_CALENDAR_SEEKER_BEGIN = 'BEG'
CALLBACK_CALENDAR_SEEKER_NEXT = 'NXT'
CALLBACK_LASTACTION_UNKNOWN = '---'
CALLBACK_MALFORM_STRING = 'Malform callback string'
CALLBACK_INTENTION_UNKNOWN = '0'
CALLBACK_INTENTION_BOOK = '1'
CALLBACK_INTENTION_BLOCKBOOK = '2'
CALLBACK_INTENTION_LISTBOOKING = '3'
CALLBACK_INTENTION_CANCELBOOKING = '4'
CALLBACK_INTENTION_NOTIFYBOOKING = '5'
CALLBACK_INTENTION_LOCK = '6'
CALLBACK_INTENTION_OVERVIEW = '7'
HANDLER_INTERNAL_BOOKBYTIME_ID = 'HANDLER_INTERNAL_BOOKBYTIME_ID'
HANDLER_INTERNAL_BOOKBYTIME_REASON_ID = 'HANDLER_INTERNAL_BOOKBYTIME_REASON_ID'
HANDLER_INTERNAL_LISTBOOKING_ID = 'HANDLER_INTERNAL_LISTBOOKING_ID'
HANDLER_INTERNAL_CANCELBOOKING_ID = 'HANDLER_INTERNAL_CANCELBOOKING_ID'
HANDLER_INTERNAL_OVERVIEW_ID = 'HANDLER_INTERNAL_OVERVIEW_ID'
HANDLER_INTERNAL_LOCK_ID = 'HANDLER_INTERNAL_LOCK_ID'
HANDLER_INTERNAL_BLOCKBOOK_ID = 'HANDLER_INTERNAL_BLOCKBOOK_ID'
HANDLER_INTERNAL_BLOCKBOOK_REASON_ID = 'HANDLER_INTERNAL_BLOCKBOOK_REASON_ID'
HANDLER_INTERNAL_REGISTRATION_ID = 'HANDLER_INTERNAL_REGISTRATION_ID'
HANDLER_INTERNAL_REGISTRATION_ACCEPT_ID = 'HANDLER_INTERNAL_REGISTRATION_ACCEPT_ID'
HANDLER_INTERNAL_HELP = 'HANDLER_INTERNAL_HELP'
HANDLER_INTERNAL_REMINDER_ID = 'HANDLER_INTERNAL_REMINDER_ID'
HANDLER_INTERNAL_TS_SUBMIT_ID = 'HANDLER_INTERNAL_TS_SUBMIT_ID'
HANDLER_INTERNAL_TS_REG_ISSUE_ID = 'HANDLER_INTERNAL_TS_REG_ISSUE_ID'
HANDLER_INTERNAL_TS_TEXT_ENTRY_ID = 'HANDLER_INTERNAL_TS_TEXT_ENTRY_ID'
FEEDBACK_KB_TS_SUBMIT_SEND_CONFIRMATION = 'Submit ticket?'
FEEDBACK_KB_REQUEST_PHONE = 'Continue to register with phone number?'
FEEDBACK_KB_OVERVIEW_SELECT_DATE_START = 'Overview start date:'
FEEDBACK_KB_OVERVIEW_SELECT_DATE_END = 'Overview end date:'
FEEDBACK_KB_OVERVIEW_SEND_CONFIRMATION = 'Send overview request?'
FEEDBACK_KB_BOOK_SELECT_ROOM_CAPACITY = 'Book room capacity:'
FEEDBACK_KB_BOOK_SELECT_ROOM_LOCATION = 'Book room location:'
FEEDBACK_KB_BOOK_SELECT_DATE = 'Book date:'
FEEDBACK_KB_BOOK_SELECT_TIME_START = 'Book start time:'
FEEDBACK_KB_BOOK_SELECT_TIME_END = 'Book end time:'
FEEDBACK_KB_BOOK_SELECT_ROOM = 'Book room:'
FEEDBACK_KB_BOOK_SEND_CONFIRMATION = 'Send book confirmation?'
FEEDBACK_KB_BLOCKBOOK_SELECT_ROOM_CAPACITY = 'Block book room capacity:'
FEEDBACK_KB_BLOCKBOOK_SELECT_ROOM_LOCATION = 'Block book room location:'
FEEDBACK_KB_BLOCKBOOK_SELECT_DURATION = 'Num of working days:'
FEEDBACK_KB_BLOCKBOOK_SELECT_DATE = 'Block book start date:'
FEEDBACK_KB_BLOCKBOOK_SELECT_ROOM = 'Block book room:'
FEEDBACK_KB_BLOCKBOOK_SELECT_USAGE = 'Usage:'
FEEDBACK_KB_BLOCKBOOK_SEND_CONFIRMATION = 'Send block book request?:'
FEEDBACK_KB_LOCK_SELECT_DATE_START = 'Lock start date:'
FEEDBACK_KB_LOCK_SELECT_DATE_END = 'Lock end date:'
FEEDBACK_KB_LOCK_SELECT_TIME_START = 'Lock start time:'
FEEDBACK_KB_LOCK_SELECT_TIME_END = 'Lock end time:'
FEEDBACK_KB_LOCK_SELECT_ROOM = 'Lock room:'
FEEDBACK_KB_LOCK_SEND_CONFIRMATION = 'Send lock request?'
FEEDBACK_KB_LIST_SELECT_RANGE = 'Listing range:'
FEEDBACK_KB_CANCEL_SELECT_RANGE = 'Listing range for cancellation:'
FEEDBACK_KB_CANCEL_BOOKING = 'Cancel booking:'
FEEDBACK_KB_CANCEL_SEND_CONFIRMATION = 'Send cancel request?'
FEEDBACK_KB_BOOKING_REQUEST_APPROVAL = 'Request approval:'
FEEDBACK_TEXT_MAINTENANCE_MODE = '<b>***** Notice *****</b>\nApp in maintenance mode.\nPlease do your booking through admin.\n\nWe will notify through Telegram once the App is up. Sorry for any inconvenience cause'
FEEDBACK_TEXT_APP_FAILURE = 'App failure'
FEEDBACK_TEXT_CONTACT_ADMIN = 'Please raise support ticket to @ISS_RoomBookingSupportBot with the following error code:'
FEEDBACK_TEXT_NOT_ADMIN = 'Require admin access'
FEEDBACK_TEXT_QUOTA_REACH = 'Reach booking quota'
FEEDBACK_TEXT_REGISTRATION = 'Please register by typing /register'
FEEDBACK_TEXT_REGISTRATION_SUCCESS = 'Register successfully'
FEEDBACK_TEXT_BLACKLISTED = 'Function is blocked'
FEEDBACK_TEXT_NO_MORE_DATE = 'No availabe dates for booking'
FEEDBACK_TEXT_NO_MORE_TIMESLOT = 'No more timeslot'
FEEDBACK_TEXT_NO_MORE_ROOM = 'All rooms booked'
FEEDBACK_TEXT_BOOKING_CANCEL = 'Cancel successfully'
FEEDBACK_TEXT_BOOKING_UPDATED = 'Booking updated'
FEEDBACK_TEXT_BOOKING_SENT = 'Booking sent'
FEEDBACK_TEXT_BOOKING_NOT_FOUND = 'No booking found'
FEEDBACK_TEXT_BOOKING_REJECTED = 'Booking rejected'
FEEDBACK_TEXT_BOOKING_INCOMING = 'Incoming booking:'
FEEDBACK_TEXT_BOOKING_NOTIFY_ADMIN_CANCELLATION = 'User booking cancellation:'
FEEDBACK_TEXT_BOOKING_NOTIFY_USER_BOOKINGID = 'Your booking ID:'
FEEDBACK_TEXT_BOOKING_ARPPROVE_ADMIN = 'Approval successful'
FEEDBACK_TEXT_BOOKING_ARPPROVE_USER = 'Approve booking ID:'
FEEDBACK_TEXT_BOOKING_REJECT_ADMIN = 'Rejection successful'
FEEDBACK_TEXT_BOOKING_REJECT_USER = 'Reject booking ID:'
FEEDBACK_TEXT_LOCK_WITHOUT_CONFLICT = 'Room is locked with no conflicting booking'
FEEDBACK_TEXT_LOCK_WITH_CONFLICT = 'Room is locked with conflicting bookings:'
FEEDBACK_TEXT_ONECLICKBOOK_INVALID_ARGUMENT_COUNT = 'Invalid argument count'
FEEDBACK_TEXT_ONECLICKBOOK_INVALID_ROOM_NAME = 'Invalid room name'
FEEDBACK_TEXT_ONECLICKBOOK_INVALID_START_DATE = 'Invalid start date'
FEEDBACK_TEXT_ONECLICKBOOK_INVALID_SLOT = 'Slot not open for booking'
FEEDBACK_TEXT_ONECLICKBOOK_INVALID_START_TIME = 'Invalid start time'
FEEDBACK_TEXT_ONECLICKBOOK_INVALID_END_TIME = 'Invalid end time'
FEEDBACK_TEXT_ONECLICKBOOK_INVALID_HISTORICAL_TIME = 'Past booking not allow'
FEEDBACK_TEXT_ONECLICKBOOK_INVALID_TIME_ORDER = 'Invalid timing order'
FEEDBACK_TEXT_ONECLICKBOOK_INVALID_WORKING_DAYS = 'Maximum working days (5) exceeded'
FEEDBACK_TEXT_ONECLICKBOOK_INVALID_WORKING_DAY_FORMAT = 'Invalid working day format'
FEEDBACK_TEXT_TS_ENTER_TICKET = 'Enter ticket details:'
FEEDBACK_TEXT_TS_ENTER_EMAIL = 'Enter company email:'
SUPPRESS_BUTTON_MULTI_CLICK_EXCEPTION = 'Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message'

MSG_RES_GENERAL_NO_ERROR_CODE = 0

NOTIF_APP_NOT_ADMIN = 'This function is for Admin ONLY.'
NOTIF_BOOKING_SLOT_TAKEN = 'The booking slot has been taken. Please try again.'

ERROR_CODE_APP___DO_MANUAL_IMPORT = 11

ERROR_CODE_MSG_GENERAL_FAILURE = 0100

ERROR_CODE_MSG_INVALID_ID = 0101

INFO_CODE_DB_BOOKING_OVERLAP = 101

ERROR_CODE_DB_BOOKING_INSERT = 1101
ERROR_CODE_DB_BOOKING_GET = 1201
ERROR_CODE_DB_BOOKING_GET_ALL_DATETIME = 1202
ERROR_CODE_DB_BOOKING_GET_USER_LISTING = 1203
ERROR_CODE_DB_BOOKING_GET_USER_BOOKING = 1204
ERROR_CODE_DB_BOOKING_GET_REPORT = 1205
ERROR_CODE_DB_BOOKING_GET_LOCK_CONFLICTED = 1206
ERROR_CODE_DB_BOOKING_GET_HAS_LOCK = 1207
ERROR_CODE_DB_BOOKING_UPDATE = 1301
ERROR_CODE_DB_BOOKING_UPDATE_STATUS = 1302
ERROR_CODE_DB_BOOKING_DEL = 1401
ERROR_CODE_DB_BOOKING_DEL_RECORD_NOT_FOUND = 1402
ERROR_CODE_DB_BOOKING_DEL_RECORD_RETRIEVAL = 1403
ERROR_CODE_DB_BOOKING_DEL_NO_RECORD_FOUND = 1404

ERROR_CODE_DB_ROOM_GENERAL = 2200
ERROR_CODE_DB_ROOM_GET_INFO = 2201
ERROR_CODE_DB_ROOM_GET_ID = 2202
ERROR_CODE_DB_ROOM_GET_INFO_ALL = 2203
ERROR_CODE_DB_ROOM_GET_NAME = 2204
ERROR_CODE_DB_ROOM_GET_INFO_REMINDER = 2205
ERROR_CODE_DB_ROOM_GET_CAPACITY = 2206
ERROR_CODE_DB_ROOM_IS_RESERVED = 2501

ERROR_CODE_DB_USER_CREATE = 3101
ERROR_CODE_DB_USER_GET_ADMIN_CHAT_ID = 3201
ERROR_CODE_DB_USER_QUOTA_EXCEEDED = 3202
ERROR_CODE_DB_USER_SAVE_UNREGISTERED = 3203
ERROR_CODE_DB_USER_GET_ALL_CHAT_ID = 3204

ERROR_CODE_DB_TICKET_OPEN = 3301

ERROR_CODE_DB_USER_IS_VALID = 3501
ERROR_CODE_DB_USER_IS_USER = 3502
ERROR_CODE_DB_USER_IS_ADMIN = 3503
ERROR_CODE_DB_USER_MISSING_USER_ID = 3504
ERROR_CODE_DB_USER_MISSING_ADMIN_ID = 3505
ERROR_CODE_DB_USER_IS_BLACKLISTED = 3506
ERROR_CODE_DB_USER_IS_UNREGISTERED = 3507

ERROR_CODE_DB_IS_VALID_CHAT_ID = 3601

ERROR_CODE_RULE_NOT_IN_ACL = 4001
ERROR_CODE_DB_ACL_IS_ADMIN_CHECK = 4002

ERROR_CODE_DB_DO_BOOKING = 6001
ERROR_CODE_DB_DO_BOOKING_SNATCHED = 6002
ERROR_CODE_DB_DO_REG = 6003
ERROR_CODE_DB_DO_LOCK = 6101

ERROR_CODE_RULE_NO_AFTER_HOUR_BOOKING = 8001
ERROR_CODE_RULE_NO_AVAIL_ROOM = 8002

ERROR_CODE_MSG_MISSING_PARAM = 9001

ERROR_CODE_DB_RECREATE_INSERT = 9901
ERROR_CODE_DB_RECREATE_UPDATE = 9902
ERROR_CODE_DB_RECREATE_DELETE = 9903

ERROR_CODE_WEB_TEXT = 10001
ERROR_CODE_WEB_BUTTON = 10002
ERROR_CODE_WEB_BOOKBYTIME = 10003
ERROR_CODE_WEB_REGISTER = 10004
ERROR_CODE_WEB_CONTACT = 10005
ERROR_CODE_WEB_LISTBOOKING = 10006
ERROR_CODE_WEB_CANCELBOOKING = 10007
ERROR_CODE_WEB_OVERVIEW = 10008
ERROR_CODE_WEB_LOCK = 10010
ERROR_CODE_WEB_BLOCKBOOK = 10011
ERROR_CODE_WEB_HELP = 10012

DB_ENUM_TICKET_STATUS_PENDING = 'pending'
DB_ENUM_TICKET_STATUS_OPENED = 'opened'
DB_ENUM_TICKET_STATUS_INPROGRESS = 'inprogress'
DB_ENUM_TICKET_STATUS_CLOSED = 'closed'
DB_ENUM_TICKET_STATUS_REJECTED = 'rejected'
DB_ENUM_BOOKING_STATUS_REQUESTED = 'requested'
DB_ENUM_BOOKING_STATUS_APPROVED = 'approved'
DB_ENUM_BOOKING_STATUS_REJECTED = 'rejected'
DB_ENUM_BOOKING_STATUS_CANCELLED = 'cancelled'
DB_ENUM_BOOKING_STATUS_LOCKED = 'locked'
DB_ENUM_USER_ROLE_ADMIN = 'admin'
DB_ENUM_USER_ROLE_USER = 'user'
DB_NOTIF_CONSTRAINT_BOOKING_OVERLAP = 'overlaps with existing reservation'
RECORDING_IDENTIFIER_TELEGRAM_INCOMING = 'REPLAY_ID_TELEGRAM_INCOMING'
RECORDING_IDENTIFIER_POSTGRES_CALLBACK = 'REPLAY_ID_POSTGRES_CALLBACK'

APP_HELP_CONTENT = """
/list
- list active bookings

/book
- step-wise fashion booking

/cancel
- cancel active bookings

/blockbook
- step-wise fasion block booking

/register
- register phone with server

/lock (require admin access)

<b>***** 1 click booking *****</b>

/book [room] [DDMMYY] [HH] [HH] [reason]
/book Ruby 291019 9 13 CDR meeting

/blockbook [room] [DDMMYY] [workingDays] [reason]
/blockbook Ruby 251019 2 ICD review

<b>***** Support ticket *****</b>

Please raise support ticket using @ISS_RoomBookingSupportBot
        """

APP_BOOK_CONTRAINTS = """
Rooms <b>NOT available</b> for booking:
<b>Amethyst</b>
<b>Amber</b>
<b>Diamond</b>
<b>Topaz</b>
Contact admin for booking

Rooms open for booking:
Interview1
Interview2
Ruby
Sapphire
Tender2
Emerald
Jade
Onyx
"""

APP_UPCOMING_RELEASE_REMINDER = '<b>***** Reminder *****</b>\nUpcoming booking for tomorrow. Please release the room if not needed to avoid being blacklisted'

APP_BOOK_RELEASE_REMINDER = '<b>***** Reminder *****</b>\nAll bookings are tracked. Please release the room if not needed to avoid being blacklisted'

APP_REGISTRATION_CONTRAINTS = """
<b>***** Note *****</b>
Your registration may fail if your phone number is not updated in our approved list

Please raise support ticket using @ISS_RoomBookingSupportBot with your company Email and we will update the list accordingly
"""

"""
Web Service Constants
"""
LOGIN_CONSEC_FAILURE_MAX = 20
UPLOAD_MAX_FILE_SIZE = 32 * 1024 * 1024     # 32 Mb

ERROR_CODE_WS_DB_LOGIN_VERIFY = 11001
ERROR_CODE_WS_DB_LOGIN_USERLOCKED = 11002
ERROR_CODE_WS_DB_LOGIN_NEWKEY = 11003
ERROR_CODE_WS_DB_LOGIN_FAILURE_UPDATE = 11004
ERROR_CODE_WS_DB_LOGIN_WRONG = 11005
ERROR_CODE_WS_DB_LOGOUT = 11006
ERROR_CODE_WS_DB_LOGOUT_SESSUNKNOWN = 11007
ERROR_CODE_WS_DB_GETSESS = 11008
ERROR_CODE_WS_DB_VALIDATE_SESSUNKNOWN = 11009
ERROR_CODE_WS_DB_UPDATE_VALIDATION_TS = 11010
ERROR_CODE_WS_DB_USER_GET_QUOTA = 11011
ERROR_CODE_WS_DB_GET_ALL_BOOKINGS = 11012
ERROR_CODE_WS_DB_USER_GET_BOOKINGS = 11013
ERROR_CODE_WS_DB_GET_ALL_BOOKINGS_GET_SESS = 11014

ERROR_CODE_WS_DB_ADMIN_CANCEL_BOOKING = 11016
ERROR_CODE_WS_DB_USER_CANCEL_BOOKING = 11017
ERROR_CODE_WS_DB_GET_ROOMS = 11018
ERROR_CODE_WS_DB_CHANGE_PASSWORD_GETHASH = 11019
ERROR_CODE_WS_DB_CHANGE_PASSWORD_WRONG_PASS = 11020
ERROR_CODE_WS_DB_CHANGE_PASSWORD_UPDATE_HASH = 11021
ERROR_CODE_WS_DB_GET_WS_USER_INFO_BY_SESS1 = 11022
ERROR_CODE_WS_DB_GET_WS_USER_INFO_BY_SESS2 = 11023
ERROR_CODE_WS_DB_GET_ACL_HISTORY = 11024
ERROR_CODE_WS_DB_UPDATE_ACL_HISTORY_EXPORT = 11025

ERROR_CODE_DB_UPDATE_USERS_BY_ACL = 12001
ERROR_CODE_DB_BLACKLIST_USERS_BY_ACL = 12002
ERROR_CODE_DB_BLACKLIST_WS_USERS_BY_ACL = 12003
ERROR_CODE_DB_UPDATE_BOOKINGS_BY_USER_STATUS = 12004
ERROR_CODE_DB_GET_ACL_WITHOUT_WS_USER = 12005
ERROR_CODE_DB_INSERT_WS_USER_BY_ACL = 12006
ERROR_CODE_DB_GET_EMPLOYEE_ID_BY_PHONE_NUMBER = 12007

DB_ENUM_BOOKING_STATUS_INVALIDATED = 'invalidated'

NOTIF_WS_USER_LOCKED = 'Your account has been locked! Please contact tech support'
NOTIF_WS_LOGIN_WRONG = 'Incorrect username/password'
NOTIF_WS_USER_WRONG_PASS = 'Incorrect old password'
NOTIF_WS_USER_LOGOUT = 'You are logged out'
NOTIF_WS_USER_QUOTA_REACHED = 'Your booking quota has already been reached!'
