TEST_ENVIRONMENT = 'JOHN'  # PRODUCTION PLAYBACK JC DL JOHN
IN_MAINTENANCE_MODE = False

DB_USER = 'postgres'
DB_USER_PASSWORD = '12345'
DB_HOST = 'localhost'
DB_PORT = '5432'
DB_NAME = 'mib'

# WEB SERVICE
WS_SCRIPTS_DIR = '/scripts'
WS_FILE_UPLOAD_DIRECTORY = './uploads'