version: "2.4"
services:
  prometheus:
    restart: always
    image: prom/prometheus:v2.15.1
    hostname: prometheus
    cpus: 2.0
    mem_limit: 2048m
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=10d
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.enable-lifecycle 
    volumes:
      - ./data/prometheus/db:/prometheus
      - ./data/prometheus/config:/etc/prometheus
    environment:
      TZ: Asia/Singapore
    ports:
      - 127.0.0.1:9090:9090

  alertmanager:
    restart: always
    image: prom/alertmanager:v0.20.0
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/alertmanager
      # Fixes this issue https://github.com/prometheus/alertmanager/issues/1814
      - --cluster.listen-address=
    hostname: alertmanager
    cpus: 0.5
    mem_limit: 256m
    volumes:
      - ./data/alertmanager:/etc/alertmanager
    environment:
      TZ: Asia/Singapore
    ports:
      - 127.0.0.1:9093:9093
    networks:
      - default

  grafana:
    restart: always
    image: grafana/grafana:6.6.2
    hostname: grafana
    cpus: 2.0
    mem_limit: 2048m
    volumes:
      - ./data/grafana/config:/etc/grafana
      - ./data/grafana/db:/var/lib/grafana
    ports:
      - "3000:3000"
