- name: Wait for automatic system updates to complete
  become: yes
  shell: "while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done;"
  changed_when: False

- name: apt install dependencies
  apt:
    name:
      - python
      - python-pip
      - python-psycopg2
      - libpq-dev
      - nodejs
      - npm
      - postgresql
      - docker.io

- name: npm install dependencies
  npm:
    name: "{{item}}"
    global: yes
  loop:
    - serve
    - webpack
    - webpack-dev-server

- name: pip install dependencies
  pip:
    name:
      - docker==4.2.0
      - docker-compose==1.25.4

- name: pip install webgui requirements
  pip:
    requirements: /opt/MiB/WebGUI/backend/backend_server/requirements.txt
