- name: Create db directory for Prometheus & Grafana
  file:
    path: /opt/MiB/data/{{item}}
    owner: nobody
    group: nogroup
    state: directory
    recurse: yes
  with_items:
    - prometheus/db

- name: Change Grafana config & db directory ownership
  file:
    path: /opt/MiB/data/grafana/{{item}}
    owner: 472
    group: 472
    state: directory
    recurse: yes
  with_items:
    - config
    - db

- name: Pull required MiB service docker images
  shell: docker-compose pull
  args:
    chdir: /opt/MiB/
